In [1]:
print("hello world")

hello world


In [2]:
%tensorflow_version 2.x


TensorFlow 2.x selected.


In [0]:
import tensorflow as tf


In [4]:
tf.__version__

'2.1.0'

In [0]:
#in this case tensor flow was just to get started with the set up 

###Note: The instructor have made 4 different Jupyter Notebooks to explain this topic , but i have combined all of them in single notebook. I have made heading wherever necessary

### Numpy arrays

In [0]:
import numpy as np


In [0]:
mylist = [1,2,3]

In [7]:
np.array(mylist)

array([1, 2, 3])

In [0]:
nested_list = [[1,2],[3,4],[5,6]]

In [9]:
nested_list

[[1, 2], [3, 4], [5, 6]]

In [10]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
#there are lost of builtin ways to generate arrays 

In [12]:
np.arange(0,10)# we will get an array of 0 to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# if want all the even number 
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
 #in data science there are many cases where we want a array of zeros , so in order to quickly create a array 
np.zeros(3)

array([0., 0., 0.])

In [15]:
#if we want 2d or 3d array or any size of matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
#and similar to np.zeros we can also get ones(1)
np.ones(2)

array([1., 1.])

In [17]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(2,10,21) #gives evenly spaced pionts 

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. ])

In [19]:
np.eye(5)#gives diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(2)#will give 2 different random numbers between 0 and 1

array([0.97462984, 0.82343776])

In [21]:
np.random.rand(3,4) #gives matrix of random numbers 

array([[0.44209775, 0.83156383, 0.59104781, 0.82352472],
       [0.64605059, 0.61743718, 0.85977237, 0.39661325],
       [0.38930765, 0.58441362, 0.8437667 , 0.41815663]])

In [22]:
#randn, includes -ve numbers also
np.random.randn(5,5)

array([[ 0.07988447,  0.06118006,  0.46314998,  0.87688493,  1.26381793],
       [ 0.17677279, -0.0056625 , -1.43187607,  0.26726793, -1.48046764],
       [-2.02830592, -0.21645269,  0.32517903, -0.03657021,  1.33110068],
       [ 0.38165876, -1.11862994,  0.44420605, -0.13694499,  0.58941632],
       [ 0.11401183,  1.13188254, -0.03179381,  0.43556783,  0.28870943]])

In [23]:
np.random.randint(1,100)# it will generate random integer between 1 and 100


92

In [24]:
np.random.randint(1,100,10)#it will generate 10 random numbers between 1 to 100

array([14, 54, 90, 35, 60, 47,  6, 64, 34, 35])

In [25]:
#in order to create an matrix of random numbers 
np.random.randint(1,100,(2,3))

array([[60, 34, 39],
       [19, 97, 30]])

In [27]:
#seed allows us to get same random values for the instructor and us 
np.random.seed(42) 
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [0]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [32]:
arr.shape

(25,)

In [35]:
#reshaping the arr
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
arr = arr.reshape(5,5)

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [39]:
ranarr.max()

39

In [40]:
ranarr.min()

2

In [41]:
#index location of max
ranarr.argmax()

7

In [43]:
#min value location
ranarr.argmin()

9

In [44]:
ranarr.dtype

dtype('int64')

### Numpy Index Selection

In [0]:
import numpy as np


In [0]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[8]#grabs whatever is at number 8 

8

In [51]:
arr[0:4]#it will go up to but not including the last   

array([0, 1, 2, 3])

In [52]:
arr[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
arr[:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[5:]#will go to the index all the way to end 

array([ 5,  6,  7,  8,  9, 10])

##### Brodcasting In Python

In [0]:
# we can replace some of the values in the array or list, with which we can not do in normal python 

#for examople 

arr[1:5] = 100

In [57]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [0]:
# In the above code we have got 100 at position form 1:5, that means 100 has been brodcasted 

In [0]:
#We will take new array
arr = np.arange(0,11) 

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_of_arr = arr[0:5]

In [63]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
slice_of_arr[:] = 99#we have selected all the arrays of the column
#in this code we have replaced the whole array with 99

In [68]:
slice_of_arr 

array([99, 99, 99, 99, 99])

In [69]:
arr


array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [0]:
arr_copy = arr.copy() #this will help us to make a copy of array , keep the original array unultered 

In [0]:
arr_copy[:] = 100

In [73]:
arr_copy#all the elemets in the array are replaced with 100

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [75]:
arr
#but the main array is un ultered 


array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

#### Indexing In 2-d Array

In [0]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [79]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
#shape of the array
arr_2d.shape

(3, 3)

In [84]:
arr_2d[1,1] #dont get confused , because in python the numbering starts with 0 not 1

5

In [85]:
#if we want 3
arr_2d[0,2]

3

In [86]:
arr_2d[:2,1]# all the rows upto 2, that means we get 0 and 1 rows, 1st column

array([2, 5])

#### Conditional Statements 

In [0]:
arr = np.arange(0,11)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr>5 #returns boolean 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [0]:
bool_arr = arr>4

In [92]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [94]:
arr[bool_arr] #will return all the values greater than 4 

array([ 5,  6,  7,  8,  9, 10])

### Numpy Operations

In [0]:
import numpy as np


In [0]:
arr = np.arange(0,11)

In [97]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr +5 #will add 5 to all the elemets in array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [100]:
arr -2 

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [102]:
arr + arr #doubles 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
arr -arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [105]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
#what happens when we divide array /array??


In [106]:
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
# we will still get a output but 0/0 will be consodered as NaN(not  a number )

According to the arithematic opreation in python , 1/0 will be error , right 


SO, What could happen when we try to divide 1 / arr??


Lets see

In [110]:
1 / 0

ZeroDivisionError: ignored

In [108]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
1 / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

So, as we have seen that, numpy will not give full error, it will only give some warnings 

Numpy comes with many universal array functions

In [111]:
np.sqrt(arr)#square root 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [112]:
np.sin(arr) #trignometric functions

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [113]:
np.log(arr) # we can use logerihemic function

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [115]:
arr.sum() #sum of all elements 

55

In [117]:
arr.mean() # mean of the arr

5.0

In [118]:
 arr
 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
arr.max()#maximum number of array

10

In [120]:
arr.min()# minimum number in array

0

In [121]:
arr.std()#standard deviation

3.1622776601683795

Lets go ahead and create 2 dimensional arrays 

In [0]:
arr2d = np.arange(0,25).reshape(5,5)

In [129]:
arr2d.sum()#it will take axis parameter,ie, either we want to add along rows or columns 

300

In [131]:
arr2d.sum(axis=0)#axis = 0, that performs the action across the rows

array([50, 55, 60, 65, 70])

In [133]:
arr2d.sum(axis=1) #performs action along accross columns 

array([ 10,  35,  60,  85, 110])